-- Create dogs table with comprehensive structure
CREATE TABLE public.dogs (
  id uuid NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  name text NOT NULL,
  breed text NOT NULL CHECK (breed IN ('australian_shepherd', 'pomeranian', 'rottweiler')),
  age text NOT NULL,
  birth_date date NOT NULL,
  color text NOT NULL,
  gender text NOT NULL CHECK (gender IN ('male', 'female')),
  status text NOT NULL CHECK (status IN ('garanhao', 'reprodutora', 'jovem_promessa', 'aposentado', 'disponivel')),
  weight decimal(5,2) NOT NULL CHECK (weight > 0),
  height decimal(5,2) NOT NULL CHECK (height > 0),
  image_url text,
  images text[] DEFAULT '{}',
  description text NOT NULL,
  temperament text NOT NULL,
  health_status text NOT NULL,
  vaccination_status text NOT NULL,
  microchip text,
  pedigree text,
  achievements text[] DEFAULT '{}',
  parents jsonb DEFAULT '{}',
  offspring text[] DEFAULT '{}',
  medical_records jsonb DEFAULT '{}',
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  is_active boolean NOT NULL DEFAULT true,
  is_available_for_breeding boolean NOT NULL DEFAULT false,
  price decimal(10,2),
  notes text
);

-- Enable Row Level Security
ALTER TABLE public.dogs ENABLE ROW LEVEL SECURITY;

-- Create policies for dogs table
CREATE POLICY "Dogs are publicly readable" 
ON public.dogs 
FOR SELECT 
USING (is_active = true);

CREATE POLICY "Admins can manage dogs" 
ON public.dogs 
FOR ALL 
USING (
  ( SELECT profiles.role
   FROM profiles
  WHERE (profiles.id = auth.uid())) = 'admin'::text
);

-- Create trigger for automatic timestamp updates
CREATE TRIGGER update_dogs_updated_at
BEFORE UPDATE ON public.dogs
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

-- Insert mock data
INSERT INTO public.dogs (
  id, name, breed, age, birth_date, color, gender, status, weight, height, 
  image_url, description, temperament, health_status, vaccination_status, 
  microchip, pedigree, achievements, parents, offspring, medical_records,
  is_active, is_available_for_breeding, price, notes
) VALUES 
-- Australian Shepherds
(
  '550e8400-e29b-41d4-a716-446655440001',
  'Luna',
  'australian_shepherd',
  '3 anos',
  '2021-05-15',
  'Blue Merle',
  'female',
  'reprodutora',
  25.5,
  55.0,
  '/placeholder.svg',
  'Luna é uma fêmea excepcional com excelente temperamento e linhagem campeã. Possui estrutura perfeita e movimentação elegante.',
  'Dócil, inteligente, leal',
  'Excelente',
  'Em dia',
  'BR1234567890',
  'CBKC-AS-12345',
  '{"Campeã Regional 2023", "Melhor Fêmea 2022", "BOB São Paulo 2023"}',
  '{"father": "Champion Max Blue", "mother": "Lady Merle Queen"}',
  '{"Puppy Luna 1", "Puppy Luna 2"}',
  '{"exams": ["Displasia coxofemoral - Normal", "Exame oftalmológico - Normal"], "vaccinations": ["V10 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  true,
  8000.00,
  'Excelente para reprodução'
),
(
  '550e8400-e29b-41d4-a716-446655440002',
  'Thor',
  'australian_shepherd',
  '4 anos',
  '2020-03-10',
  'Red Tri',
  'male',
  'garanhao',
  32.0,
  60.0,
  '/placeholder.svg',
  'Thor é nosso garanhão principal, conhecido por sua beleza e temperamento equilibrado. Possui linhagem internacional.',
  'Equilibrado, ativo, protetor',
  'Excelente',
  'Em dia',
  'BR1234567891',
  'CBKC-AS-12346',
  '{"Grande Campeão 2023", "Melhor Macho 2022", "BIS 2021", "Champion Internacional"}',
  '{"father": "Grand Champion Red Storm", "mother": "Beauty Red Princess"}',
  '{"Thor Jr.", "Red Beauty", "Storm Lightning"}',
  '{"exams": ["Displasia coxofemoral - Normal", "Cardio - Normal"], "vaccinations": ["V10 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  true,
  12000.00,
  'Reprodutor premiado'
),
(
  '550e8400-e29b-41d4-a716-446655440003',
  'Stella',
  'australian_shepherd',
  '2 anos',
  '2022-08-20',
  'Black Tri',
  'female',
  'jovem_promessa',
  22.0,
  52.0,
  '/placeholder.svg',
  'Stella é uma jovem promissora com excelente estrutura e movimento. Filha de campeões.',
  'Alegre, inteligente, ativa',
  'Excelente',
  'Em dia',
  'BR1234567892',
  'CBKC-AS-12347',
  '{"Melhor Filhote 2023", "Promessa do Ano", "Winner Junior"}',
  '{"father": "Thor", "mother": "Black Beauty Champion"}',
  '{}',
  '{"exams": ["Exames básicos - Normal"], "vaccinations": ["V10 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  false,
  6000.00,
  'Grande potencial futuro'
),
-- Pomeranians
(
  '550e8400-e29b-41d4-a716-446655440004',
  'Bella',
  'pomeranian',
  '2 anos',
  '2022-01-10',
  'Orange Sable',
  'female',
  'reprodutora',
  2.5,
  18.0,
  '/placeholder.svg',
  'Bella é uma lulu encantadora com pelagem exuberante e temperamento doce. Perfeita estrutura de raça.',
  'Doce, alerta, carinhosa',
  'Excelente',
  'Em dia',
  'BR1234567893',
  'CBKC-POM-12345',
  '{"Melhor Fêmea Jovem 2023", "Campeã de Beleza", "BOB Nacional"}',
  '{"father": "Orange Prince", "mother": "Sable Queen"}',
  '{"Mini Bella 1", "Mini Bella 2"}',
  '{"exams": ["Luxação patelar - Normal", "Coração - Normal"], "vaccinations": ["V8 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  true,
  5000.00,
  'Excelente mãe'
),
(
  '550e8400-e29b-41d4-a716-446655440005',
  'Simba',
  'pomeranian',
  '3 anos',
  '2021-06-05',
  'Orange',
  'male',
  'garanhao',
  3.0,
  20.0,
  '/placeholder.svg',
  'Simba possui estrutura perfeita e movimentação elegante típica da raça. Garanhão premiado.',
  'Confiante, elegante, ativo',
  'Excelente',
  'Em dia',
  'BR1234567894',
  'CBKC-POM-12346',
  '{"Grande Campeão 2022", "Melhor Macho Adulto", "King of Orange"}',
  '{"father": "Lion King Champion", "mother": "Orange Princess"}',
  '{"Little Simba", "Orange Star", "Golden Prince"}',
  '{"exams": ["Exames completos - Normal"], "vaccinations": ["V8 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  true,
  7000.00,
  'Reprodutor de elite'
),
(
  '550e8400-e29b-41d4-a716-446655440006',
  'Mila',
  'pomeranian',
  '1 ano',
  '2023-04-12',
  'Cream',
  'female',
  'jovem_promessa',
  2.0,
  16.0,
  '/placeholder.svg',
  'Mila é nossa jovem estrela com grande potencial para reprodução. Filha de campeões.',
  'Brincalhona, doce, inteligente',
  'Excelente',
  'Em dia',
  'BR1234567895',
  'CBKC-POM-12347',
  '{"Melhor Filhote do Ano", "Revelação 2023", "Baby Winner"}',
  '{"father": "Simba", "mother": "Cream Beauty"}',
  '{}',
  '{"exams": ["Exames iniciais - Normal"], "vaccinations": ["V8 - 2024"], "treatments": []}',
  true,
  false,
  4000.00,
  'Futuro promissor'
),
-- Rottweilers
(
  '550e8400-e29b-41d4-a716-446655440007',
  'Kaiser',
  'rottweiler',
  '4 anos',
  '2020-02-28',
  'Preto e Fogo',
  'male',
  'garanhao',
  55.0,
  68.0,
  '/placeholder.svg',
  'Kaiser é um exemplar imponente com temperamento equilibrado e protetor. Linhagem alemã pura.',
  'Equilibrado, protetor, leal',
  'Excelente',
  'Em dia',
  'BR1234567896',
  'CBKC-ROT-12345',
  '{"Campeão Nacional 2023", "Melhor da Raça", "Sieger Show Winner"}',
  '{"father": "German Kaiser Von", "mother": "Black Princess Vom"}',
  '{"Kaiser Jr.", "Black Storm", "Royal Guard"}',
  '{"exams": ["Displasia coxofemoral - Normal", "Coração - Normal", "Cotovelos - Normal"], "vaccinations": ["V10 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  true,
  15000.00,
  'Reprodutor excepcional'
),
(
  '550e8400-e29b-41d4-a716-446655440008',
  'Hera',
  'rottweiler',
  '3 anos',
  '2021-07-15',
  'Preto e Fogo',
  'female',
  'reprodutora',
  42.0,
  62.0,
  '/placeholder.svg',
  'Hera combina força e elegância, sendo mãe exemplar e excelente guardiã. Temperamento perfeito.',
  'Maternal, protetora, equilibrada',
  'Excelente',
  'Em dia',
  'BR1234567897',
  'CBKC-ROT-12346',
  '{"Campeã Regional 2022", "Melhor Reprodutora", "Mother of Champions"}',
  '{"father": "Thunder Von Haus", "mother": "Hera Queen Vom"}',
  '{"Little Hera", "Black Beauty", "Strong Guardian"}',
  '{"exams": ["Displasia - Normal", "Reprodução - Apta"], "vaccinations": ["V10 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  true,
  10000.00,
  'Mãe exemplar'
),
(
  '550e8400-e29b-41d4-a716-446655440009',
  'Zeus',
  'rottweiler',
  '2 anos',
  '2022-09-03',
  'Preto e Fogo',
  'male',
  'jovem_promessa',
  45.0,
  65.0,
  '/placeholder.svg',
  'Zeus demonstra todas as qualidades desejáveis da raça desde jovem. Futuro reprodutor.',
  'Forte, confiante, obediente',
  'Excelente',
  'Em dia',
  'BR1234567898',
  'CBKC-ROT-12347',
  '{"Melhor Jovem 2023", "Promessa do Ano", "Junior Winner"}',
  '{"father": "Kaiser", "mother": "Thunder Queen"}',
  '{}',
  '{"exams": ["Exames jovem - Normal"], "vaccinations": ["V10 - 2024", "Antirrábica - 2024"], "treatments": []}',
  true,
  false,
  8000.00,
  'Futuro campeão'
);