// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iikontpccomtgytcmwnn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlpa29udHBjY29tdGd5dGNtd25uIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU3MDcxNzIsImV4cCI6MjA3MTI4MzE3Mn0.Ssyvv613_H7Xc044yX2pJfIfYQ6t5HWoOxrnB-Pg2vM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});